import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart'; // It provides "required" label

/// Entity Class
/// It defines our core data structures: texts and numbers

/// Equatable: allows value comparison between objects (in Dart, equality
/// comparison between objects is referential). Also, it allows us to avoid
/// boilerplate generated by overriding native functions (equality, hashcode, etc)
class NumberTrivia extends Equatable {
  final String text;
  final int number;

  NumberTrivia({
    @required this.text,
    @required this.number,
  }) : super([
          text,
          number
        ]); // Pass to Equatable constructor (receives a list of props)
}
