import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart'; // It provides "required" label

/// Entity Class.
/// It defines our core data structure: NumberTrivia, and object with "text" and "number"
/// attribute.
class NumberTrivia extends Equatable {
  // Equatable: allows value comparison between objects (in Dart, equality
  // comparison between objects is referential). Also, it allows us to avoid
  // boilerplate generated by overriding native functions (equality, hashcode, etc
  final String text;
  final int number;

  /// Constructor method.
  NumberTrivia({
    @required this.text,
    @required this.number,
  }) : super([
          text,
          number
        ]); // Pass to Equatable constructor (receives a list of props)
}
